name: keep3r_bot
author: valory
version: 0.1.0
description: A set of agents implementing the Autonomous Keep3r Service.
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint:
  README.md: bafybeig26ntff2vdtmum3crflwqrybmonwdxahvlrst2brnazbo3mjvtqu
fingerprint_ignore_patterns: []
agent: valory/keep3r_bot:0.1.0:bafybeid7zpebkekceqjl6ofse5tot3tpp3lw4zl3tqvjjy3754hf474jlm
number_of_agents: 1
deployment:
  tendermint:
    ports:
      0:
        26656: 26656
      1:
        26666: 26656
      2:
        26676: 26656
      3:
        26686: 26656
---
public_id: valory/keep3r_abci:0.1.0
type: skill
extra:
  params_args:
    args:
      setup: &id001
        all_participants: ${ALL_PARTICIPANTS:list:["0x0000000000000000000000000000000000000000"]}
        safe_contract_address: ${SAFE_CONTRACT_ADDRESS:str:0x0000000000000000000000000000000000000000}
      bonding_asset: ${BONDING_ASSET:str:0x0000000000000000000000000000000000000000}
      bond_amount: ${BOND_AMOUNT:int:1}
      reset_pause_duration: ${RESET_PAUSE_DURATION:int:15}
      service_registry_address: '0x48b6af7B12C71f09e2fC8aF4855De4Ff54e775cA'
      on_chain_service_id: ${ON_CHAIN_SERVICE_ID:int:null}
      share_tm_config_on_startup: ${USE_ACN:bool:false}
      sleep_time: ${SLEEP_TIME:int:3}
      use_termination: ${USE_TERMINATION:bool:false}
      use_flashbots: ${USE_FLASHBOTS:bool:true}
      reset_tendermint_after: ${RESET_TENDERMINT_AFTER:int:2}
      supported_jobs_to_package_hash: ${JOBS_TO_HASH:list:[]}
      keep3r_v1_contract_address: ${KEEP3R_V1_ADDRESS:str:0x1cEB5cB57C4D4E2b2433641b95Dd330A33185A44}
      keep3r_v2_contract_address: ${KEEP3R_V2_ADDRESS:str:0xeb02addCfD8B773A5FFA6B9d1FE99c566f8c44CC}
      use_v2: ${USE_KEEPER_V2:bool:true}
      k3pr_address: ${K3PR_ADDRESS:str:0x1cEB5cB57C4D4E2b2433641b95Dd330A33185A44}
      unbonding_threshold: ${UNBONDING_THRESHOLD:int:50}
      manual_gas_limit: ${MANUAL_GAS_LIMIT:int:5000000}
      raise_on_failed_simulation: ${RAISE_ON_FAILED_SIMULATION:bool:true}
0:
  models:
    params:
      args:
        setup: *id001
        bonding_asset: ${BONDING_ASSET:str:0x0000000000000000000000000000000000000000}
        bond_amount: ${BOND_AMOUNT:int:1}
        reset_pause_duration: ${RESET_PAUSE_DURATION:int:15}
        service_registry_address: '0x48b6af7B12C71f09e2fC8aF4855De4Ff54e775cA'
        on_chain_service_id: ${ON_CHAIN_SERVICE_ID:int:null}
        share_tm_config_on_startup: ${USE_ACN:bool:true}
        sleep_time: ${SLEEP_TIME:int:3}
        use_termination: ${USE_TERMINATION:bool:false}
        use_flashbots: ${USE_FLASHBOTS:bool:true}
        reset_tendermint_after: ${RESET_TENDERMINT_AFTER:int:2}
        supported_jobs_to_package_hash: ${JOBS_TO_HASH:list:[]}
        keep3r_v1_contract_address: ${KEEP3R_V1_ADDRESS:str:0x1cEB5cB57C4D4E2b2433641b95Dd330A33185A44}
        keep3r_v2_contract_address: ${KEEP3R_V2_ADDRESS:str:0xeb02addCfD8B773A5FFA6B9d1FE99c566f8c44CC}
        use_v2: ${USE_KEEPER_V2:bool:true}
        k3pr_address: ${K3PR_ADDRESS:str:0x1cEB5cB57C4D4E2b2433641b95Dd330A33185A44}
        unbonding_threshold: ${UNBONDING_THRESHOLD:int:50}
        tendermint_p2p_url: ${TENDERMINT_P2P_URL_0:str:node0:26656}
        manual_gas_limit: ${MANUAL_GAS_LIMIT:int:5000000}
        raise_on_failed_simulation: ${RAISE_ON_FAILED_SIMULATION:bool:true}
1:
  models:
    params:
      args:
        setup: *id001
        bonding_asset: ${BONDING_ASSET:str:0x0000000000000000000000000000000000000000}
        bond_amount: ${BOND_AMOUNT:int:1}
        reset_pause_duration: ${RESET_PAUSE_DURATION:int:15}
        service_registry_address: '0x48b6af7B12C71f09e2fC8aF4855De4Ff54e775cA'
        on_chain_service_id: ${ON_CHAIN_SERVICE_ID:int:null}
        use_termination: ${USE_TERMINATION:bool:false}
        sleep_time: ${SLEEP_TIME:int:3}
        share_tm_config_on_startup: ${USE_ACN:bool:true}
        use_flashbots: ${USE_FLASHBOTS:bool:true}
        supported_jobs_to_package_hash: ${JOBS_TO_HASH:list:[]}
        reset_tendermint_after: ${RESET_TENDERMINT_AFTER:int:2}
        keep3r_v1_contract_address: ${KEEP3R_V1_ADDRESS:str:0x1cEB5cB57C4D4E2b2433641b95Dd330A33185A44}
        keep3r_v2_contract_address: ${KEEP3R_V2_ADDRESS:str:0xeb02addCfD8B773A5FFA6B9d1FE99c566f8c44CC}
        use_v2: ${USE_KEEPER_V2:bool:true}
        k3pr_address: ${K3PR_ADDRESS:str:0x1cEB5cB57C4D4E2b2433641b95Dd330A33185A44}
        unbonding_threshold: ${UNBONDING_THRESHOLD:int:50}
        tendermint_p2p_url: ${TENDERMINT_P2P_URL_1:str:node1:26656}
        manual_gas_limit: ${MANUAL_GAS_LIMIT:int:5000000}
        raise_on_failed_simulation: ${RAISE_ON_FAILED_SIMULATION:bool:true}
2:
  models:
    params:
      args:
        setup: *id001
        bonding_asset: ${BONDING_ASSET:str:0x0000000000000000000000000000000000000000}
        bond_amount: ${BOND_AMOUNT:int:1}
        reset_pause_duration: ${RESET_PAUSE_DURATION:int:15}
        service_registry_address: '0x48b6af7B12C71f09e2fC8aF4855De4Ff54e775cA'
        on_chain_service_id: ${ON_CHAIN_SERVICE_ID:int:null}
        share_tm_config_on_startup: ${USE_ACN:bool:true}
        use_flashbots: ${USE_FLASHBOTS:bool:true}
        sleep_time: ${SLEEP_TIME:int:3}
        use_termination: ${USE_TERMINATION:bool:false}
        supported_jobs_to_package_hash: ${JOBS_TO_HASH:list:[]}
        reset_tendermint_after: ${RESET_TENDERMINT_AFTER:int:2}
        keep3r_v1_contract_address: ${KEEP3R_V1_ADDRESS:str:0x1cEB5cB57C4D4E2b2433641b95Dd330A33185A44}
        keep3r_v2_contract_address: ${KEEP3R_V2_ADDRESS:str:0xeb02addCfD8B773A5FFA6B9d1FE99c566f8c44CC}
        use_v2: ${USE_KEEPER_V2:bool:true}
        k3pr_address: ${K3PR_ADDRESS:str:0x1cEB5cB57C4D4E2b2433641b95Dd330A33185A44}
        unbonding_threshold: ${UNBONDING_THRESHOLD:int:50}
        tendermint_p2p_url: ${TENDERMINT_P2P_URL_2:str:node2:26656}
        manual_gas_limit: ${MANUAL_GAS_LIMIT:int:5000000}
        raise_on_failed_simulation: ${RAISE_ON_FAILED_SIMULATION:bool:true}
3:
  models:
    params:
      args:
        setup: *id001
        bonding_asset: ${BONDING_ASSET:str:0x0000000000000000000000000000000000000000}
        bond_amount: ${BOND_AMOUNT:int:1}
        reset_pause_duration: ${RESET_PAUSE_DURATION:int:15}
        service_registry_address: '0x48b6af7B12C71f09e2fC8aF4855De4Ff54e775cA'
        on_chain_service_id: ${ON_CHAIN_SERVICE_ID:int:null}
        share_tm_config_on_startup: ${USE_ACN:bool:true}
        use_termination: ${USE_TERMINATION:bool:false}
        use_flashbots: ${USE_FLASHBOTS:bool:true}
        sleep_time: ${SLEEP_TIME:int:3}
        reset_tendermint_after: ${RESET_TENDERMINT_AFTER:int:2}
        supported_jobs_to_package_hash: ${JOBS_TO_HASH:list:[]}
        keep3r_v1_contract_address: ${KEEP3R_V1_ADDRESS:str:0x1cEB5cB57C4D4E2b2433641b95Dd330A33185A44}
        keep3r_v2_contract_address: ${KEEP3R_V2_ADDRESS:str:0xeb02addCfD8B773A5FFA6B9d1FE99c566f8c44CC}
        use_v2: ${USE_KEEPER_V2:bool:true}
        k3pr_address: ${K3PR_ADDRESS:str:0x1cEB5cB57C4D4E2b2433641b95Dd330A33185A44}
        unbonding_threshold: ${UNBONDING_THRESHOLD:int:50}
        tendermint_p2p_url: ${TENDERMINT_P2P_URL_3:str:node3:26656}
        manual_gas_limit: ${MANUAL_GAS_LIMIT:int:5000000}
        raise_on_failed_simulation: ${RAISE_ON_FAILED_SIMULATION:bool:true}
---
public_id: valory/ledger:0.19.0
type: connection
0:
  config:
    ledger_apis:
      ethereum:
        address: ${SERVICE_RPC_0:str:http://127.0.0.1:8545}
        chain_id: 1
      ethereum_flashbots:
        flashbot_relayer_uri: ${FLASHBOTS_RELAYER_URI_0:str:https://relay.flashbots.net}
        authentication_private_key: ${FLASHBOTS_PRIVATE_KEY_0:str:null}
      arbitrum:
        address: ${ARBITRUM_RPC_0:str:http://127.0.0.1:8545}
        chain_id: ${ARBITRUM_CHAIN_ID:int:42161}
      consensys:
        address: ${CONSENSYS_RPC_0:str:http://127.0.0.1:8545}
        chain_id: ${CONSENSYS_CHAIN_ID:int:1337}
      bnb:
        address: ${BNB_RPC_0:str:http://127.0.0.1:8545}
        chain_id: ${BNB_CHAIN_ID:int:56}
      gnosis:
        address: ${GNOSIS_RPC_0:str:http://127.0.0.1:8545}
        chain_id: ${GNOSIS_CHAIN_ID:int:100}
      zksync:
        address: ${ZKSYNC_RPC_0:str:http://127.0.0.1:8545}
        chain_id: ${ZKSYNC_CHAIN_ID:int:324}
1:
  config:
    ledger_apis:
      ethereum:
        address: ${SERVICE_RPC_1:str:http://127.0.0.1:8545}
        chain_id: 1
      ethereum_flashbots:
        flashbot_relayer_uri: ${FLASHBOTS_RELAYER_URI_1:str:https://relay.flashbots.net}
        authentication_private_key: ${FLASHBOTS_PRIVATE_KEY_1:str:null}
      arbitrum:
        address: ${ARBITRUM_RPC_1:str:http://127.0.0.1:8545}
        chain_id: ${ARBITRUM_CHAIN_ID:int:42161}
      consensys:
        address: ${CONSENSYS_RPC_1:str:http://127.0.0.1:8545}
        chain_id: ${CONSENSYS_CHAIN_ID:int:1337}
      bnb:
        address: ${BNB_RPC_1:str:http://127.0.0.1:8545}
        chain_id: ${BNB_CHAIN_ID:int:56}
      gnosis:
        address: ${GNOSIS_RPC_1:str:http://127.0.0.1:8545}
        chain_id: ${GNOSIS_CHAIN_ID:int:100}
      zksync:
        address: ${ZKSYNC_RPC_1:str:http://127.0.0.1:8545}
        chain_id: ${ZKSYNC_CHAIN_ID:int:324}
2:
  config:
    ledger_apis:
      ethereum:
        address: ${SERVICE_RPC_2:str:http://127.0.0.1:8545}
        chain_id: 1
      ethereum_flashbots:
        flashbot_relayer_uri: ${FLASHBOTS_RELAYER_URI_2:str:https://relay.flashbots.net}
        authentication_private_key: ${FLASHBOTS_PRIVATE_KEY_2:str:null}
      arbitrum:
        address: ${ARBITRUM_RPC_2:str:http://127.0.0.1:8545}
        chain_id: ${ARBITRUM_CHAIN_ID:int:42161}
      consensys:
        address: ${CONSENSYS_RPC_2:str:http://127.0.0.1:8545}
        chain_id: ${CONSENSYS_CHAIN_ID:int:1337}
      bnb:
        address: ${BNB_RPC_2:str:http://127.0.0.1:8545}
        chain_id: ${BNB_CHAIN_ID:int:56}
      gnosis:
        address: ${GNOSIS_RPC_2:str:http://127.0.0.1:8545}
        chain_id: ${GNOSIS_CHAIN_ID:int:100}
      zksync:
        address: ${ZKSYNC_RPC_2:str:http://127.0.0.1:8545}
        chain_id: ${ZKSYNC_CHAIN_ID:int:324}
3:
  config:
    ledger_apis:
      ethereum:
        address: ${SERVICE_RPC_3:str:http://127.0.0.1:8545}
        chain_id: 1
      ethereum_flashbots:
        flashbot_relayer_uri: ${FLASHBOTS_RELAYER_URI_3:str:https://relay.flashbots.net}
        authentication_private_key: ${FLASHBOTS_PRIVATE_KEY_3:str:null}
      arbitrum:
        address: ${ARBITRUM_RPC_3:str:http://127.0.0.1:8545}
        chain_id: ${ARBITRUM_CHAIN_ID:int:42161}
      consensys:
        address: ${CONSENSYS_RPC_3:str:http://127.0.0.1:8545}
        chain_id: ${CONSENSYS_CHAIN_ID:int:1337}
      bnb:
        address: ${BNB_RPC_3:str:http://127.0.0.1:8545}
        chain_id: ${BNB_CHAIN_ID:int:56}
      gnosis:
        address: ${GNOSIS_RPC_3:str:http://127.0.0.1:8545}
        chain_id: ${GNOSIS_CHAIN_ID:int:100}
      zksync:
        address: ${ZKSYNC_RPC_3:str:http://127.0.0.1:8545}
        chain_id: ${ZKSYNC_CHAIN_ID:int:324}
