agent_name: keep3r_bot
author: keep3r_co
version: 0.1.0
license: Apache-2.0
description: Keep3r agent to work on Keep3r job contracts
aea_version: '>=1.0.0, <2.0.0'
fingerprint:
  README.md: bafybeih4kccfgxwkvd32bokjpqsfuyc2c3juek2g7vrsmixlfr7urgwkn4
fingerprint_ignore_patterns: []
connections:
- valory/abci:0.1.0:bafybeifjqmtdwznrzqevn2sln74xfm2gewvgneda26egg7qpokcwjwwr4y
- valory/http_client:0.1.0:bafybeigxjc25bp4vdmhuhdq6f3a5j7g2auyvaf5s3xl6eqov4mcm2jgcmu
- valory/ledger:0.1.0:bafybeieszkfizyqfxmjsgsdjj4353oxkmcjxa6knafkf5u7adh3xsgdys4
contracts:
- gabrielfu/keep3r_job:0.1.0:bafybeihgz7flasaijeachrkmpgyqdqmeawknh2nfoie2page57ejy5l4ai
protocols:
- open_aea/signing:1.0.0:bafybeicc6dd4kaalwfqreh7xhwyovg7rqy7g7tsy4oddke7ft7hbj43g4y
- valory/abci:0.1.0:bafybeiedib4f7ryh6rr3c67ymg62wshuc3kxrfx7egd3nsz6l7laaflpzi
- valory/contract_api:1.0.0:bafybeih4vhywhz25qpsskwcn34bmzs4oavqzd5hfdjbo42bjchfqt7vp6m
- valory/http:1.0.0:bafybeihtz7ctxytxlah3mw2vhdup5hbjocfgocnzz3ajsgqdyzjlwe2eku
- valory/ledger_api:1.0.0:bafybeibpni27yfhpub3mnaxoiye5sh4orfpd4aftd255bd37z2etatym6u
skills:
- keep3r_co/keep3r_abci:0.1.0:bafybeihpronxe3qkavobmibih5pj56qra7y5qrp43weuqor2cn7lptraw4
- keep3r_co/keep3r_job:0.1.0:bafybeic6nb5cmslw5kpkovoo7h4dmgikq6tz3kn7btcoaf7cikptbpqaoi
- valory/abstract_abci:0.1.0:bafybeicmwzbui3s4ouhtufcrlmmglnhgo4j2a3jdhfmqnqwlihdfubmmdq
- valory/abstract_round_abci:0.1.0:bafybeicvvipsdvzaf5yvzn74liubbsn6bgi6h3lh2i5ostexwmfxvbu4x4
- valory/registration_abci:0.1.0:bafybeidhcmvpsbgkitz42nsfi2zfnz7x3t4kcayh234wzxnrc5qdx4yb4u
- valory/reset_pause_abci:0.1.0:bafybeicyywvjvzwnjd4dxrgr3hzbjm6ydx7vzrr5vgrjjyuxhz4fh4p22y
- valory/safe_deployment_abci:0.1.0:bafybeibz4s4o4t5vw6usfwgyby4yvwn3aiy4ub2bheehpak6dwx7meajie
- valory/transaction_settlement_abci:0.1.0:bafybeiedohlymppocfahu5bt4wvquowieefmphtxs2aadzo4gzf4kpeuvq
default_ledger: ethereum
required_ledgers:
- ethereum
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  version: 1
  disable_existing_loggers: false
  formatters:
    standard:
      format: '[%(asctime)s] [%(levelname)s] %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: standard
      stream: ext://sys.stdout
  loggers:
    aea:
      handlers:
      - console
      propagate: false
dependencies:
  open-aea-ledger-ethereum: {}
default_connection: null
---
public_id: valory/abci:0.1.0
type: connection
config:
  target_skill_id: keep3r_co/keep3r_abci:0.1.0
