name: keep3r_bot
author: keep3r_co
version: 0.1.0
description: A set of agents implementing the Keep3r Bot.
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint:
  README.md: bafybeig26ntff2vdtmum3crflwqrybmonwdxahvlrst2brnazbo3mjvtqu
fingerprint_ignore_patterns: []
agent: keep3r_co/keep3r_bot:0.1.0:bafybeibfp7hlmazspviemw6qvwu4wgn5e5x7itjoog2ip43w4wggztub44
number_of_agents: 1
---
public_id: keep3r_co/keep3r_abci:0.1.0
type: skill
models:
  params:
    args:
      setup:
        all_participants: ${ALL_PARTICIPANTS:list:["0x0000000000000000000000000000000000000000"]}
        safe_contract_address: ${SAFE_CONTRACT_ADDRESS:list:["0x0000000000000000000000000000000000000000"]}
      bonding_asset: ${BONDING_ASSET:str:0x0000000000000000000000000000000000000000}
      bond_amount: ${BOND_AMOUNT:int:1}
      observation_interval: ${OBSERVATION_INTERVAL:int:15}
      service_registry_address: '0x48b6af7B12C71f09e2fC8aF4855De4Ff54e775cA'
      on_chain_service_id: ${ON_CHAIN_SERVICE_ID:int:null}
      share_tm_config_on_startup: ${USE_ACN:bool:false}
      supported_jobs_to_package_hash: ${JOBS_TO_HASH:list:[["0xa61d82a9127B1c1a34Ce03879A068Af5b786C835","bafybeihaxl5l5ltmiius3bcr5pt3tqy6fgwn56hqm7zzm3uxupj6i2xfni"],["0xEC771dc7Bd0aA67a10b1aF124B9b9a0DC4aF5F9B","bafybeieedl2oblihpkugxwothabjpzgglxf6ignvjppw6i2mclvh6j2tny"]]}
      keep3r_v1_contract_address: ${KEEP3R_V1_ADDRESS:str:0x1cEB5cB57C4D4E2b2433641b95Dd330A33185A44}
      keep3r_v2_contract_address: ${KEEP3R_V2_ADDRESS:str:0xeb02addCfD8B773A5FFA6B9d1FE99c566f8c44CC}
      use_v2: ${USE_KEEPER_V2:bool:true}
      consensus:
        max_participants: 1
---
public_id: valory/ledger:0.19.0
type: connection
0:
  config:
    ledger_apis:
      ethereum:
        address: ${SERVICE_RPC_0:str:http://127.0.0.1:8545}
        chain_id: 1
