name: keep3r_bot_goerli
author: valory
version: 0.1.0
description: A set of agents implementing the Keep3r Bot.
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint:
  README.md: bafybeiblcg3qti2cyz4ytufdkmqzcm6svbo5cwgsu2srjovvljdi35iz6i
fingerprint_ignore_patterns: []
agent: valory/keep3r_bot:0.1.0:bafybeievp77gj7f37nybdr3oxtxfnxvrsacako6wyle4jt7cpqaqr4or4a
number_of_agents: 4
deployment:
  tendermint:
    ports:
      0:
        26656: 26656
      1:
        26666: 26656
      2:
        26676: 26656
      3:
        26686: 26656
---
public_id: valory/keep3r_abci:0.1.0
type: skill
extra:
  params_args:
    args:
      setup: &id001
        all_participants: ${ALL_PARTICIPANTS:list:["0x0000000000000000000000000000000000000000"]}
        safe_contract_address: ${SAFE_CONTRACT_ADDRESS:str:0x0000000000000000000000000000000000000000}
      bonding_asset: ${BONDING_ASSET:str:0x0000000000000000000000000000000000000000}
      bond_amount: ${BOND_AMOUNT:int:1}
      reset_pause_duration: ${RESET_PAUSE_DURATION:int:60}
      service_registry_address: '0x1cEe30D08943EB58EFF84DD1AB44a6ee6FEff63a'
      on_chain_service_id: ${ON_CHAIN_SERVICE_ID:int:null}
      share_tm_config_on_startup: ${USE_ACN:bool:false}
      use_termination: ${USE_TERMINATION:bool:false}
      use_flashbots: ${USE_FLASHBOTS:bool:false}
      supported_jobs_to_package_hash: ${JOBS_TO_HASH:list:null}
      keep3r_v1_contract_address: ${KEEP3R_V1_ADDRESS:str:0x3364BF0a8DcB15E463E6659175c90A57ee3d4288}
      keep3r_v2_contract_address: ${KEEP3R_V2_ADDRESS:str:0x85063437C02Ba7F4f82F898859e4992380DEd3bb}
      participant_to_swap_pref: ${SWAP_PREF:list:[["0x0000000000000000000000000000000000000000","k3pr"]]}
      use_v2: ${USE_KEEPER_V2:bool:true}
0:
  models:
    params:
      args:
        setup: *id001
        bonding_asset: ${BONDING_ASSET:str:0x0000000000000000000000000000000000000000}
        bond_amount: ${BOND_AMOUNT:int:1}
        reset_pause_duration: ${RESET_PAUSE_DURATION:int:60}
        service_registry_address: '0x1cEe30D08943EB58EFF84DD1AB44a6ee6FEff63a'
        on_chain_service_id: ${ON_CHAIN_SERVICE_ID:int:null}
        share_tm_config_on_startup: ${USE_ACN:bool:false}
        use_termination: ${USE_TERMINATION:bool:false}
        use_flashbots: ${USE_FLASHBOTS:bool:false}
        supported_jobs_to_package_hash: ${JOBS_TO_HASH:list:null}
        keep3r_v1_contract_address: ${KEEP3R_V1_ADDRESS:str:0x3364BF0a8DcB15E463E6659175c90A57ee3d4288}
        keep3r_v2_contract_address: ${KEEP3R_V2_ADDRESS:str:0x85063437C02Ba7F4f82F898859e4992380DEd3bb}
        use_v2: ${USE_KEEPER_V2:bool:true}
        participant_to_swap_pref: ${SWAP_PREF:list:[["0x0000000000000000000000000000000000000000","k3pr"]]}
        tendermint_p2p_url: ${TENDERMINT_P2P_URL_0:str:node0:26656}
        service_endpoint_base: ${SERVICE_ENDPOINT_BASE:str:https://dummy_service.autonolas.tech/}
1:
  models:
    params:
      args:
        setup: *id001
        bonding_asset: ${BONDING_ASSET:str:0x0000000000000000000000000000000000000000}
        bond_amount: ${BOND_AMOUNT:int:1}
        reset_pause_duration: ${RESET_PAUSE_DURATION:int:60}
        service_registry_address: '0x1cEe30D08943EB58EFF84DD1AB44a6ee6FEff63a'
        on_chain_service_id: ${ON_CHAIN_SERVICE_ID:int:null}
        use_termination: ${USE_TERMINATION:bool:false}
        share_tm_config_on_startup: ${USE_ACN:bool:false}
        use_flashbots: ${USE_FLASHBOTS:bool:false}
        supported_jobs_to_package_hash: ${JOBS_TO_HASH:list:null}
        keep3r_v1_contract_address: ${KEEP3R_V1_ADDRESS:str:0x3364BF0a8DcB15E463E6659175c90A57ee3d4288}
        keep3r_v2_contract_address: ${KEEP3R_V2_ADDRESS:str:0x85063437C02Ba7F4f82F898859e4992380DEd3bb}
        use_v2: ${USE_KEEPER_V2:bool:true}
        participant_to_swap_pref: ${SWAP_PREF:list:[["0x0000000000000000000000000000000000000000","k3pr"]]}
        tendermint_p2p_url: ${TENDERMINT_P2P_URL_1:str:node1:26656}
        service_endpoint_base: ${SERVICE_ENDPOINT_BASE:str:https://dummy_service.autonolas.tech/}
2:
  models:
    params:
      args:
        setup: *id001
        bonding_asset: ${BONDING_ASSET:str:0x0000000000000000000000000000000000000000}
        bond_amount: ${BOND_AMOUNT:int:1}
        reset_pause_duration: ${RESET_PAUSE_DURATION:int:60}
        service_registry_address: '0x1cEe30D08943EB58EFF84DD1AB44a6ee6FEff63a'
        on_chain_service_id: ${ON_CHAIN_SERVICE_ID:int:null}
        share_tm_config_on_startup: ${USE_ACN:bool:false}
        use_flashbots: ${USE_FLASHBOTS:bool:false}
        use_termination: ${USE_TERMINATION:bool:false}
        supported_jobs_to_package_hash: ${JOBS_TO_HASH:list:null}
        keep3r_v1_contract_address: ${KEEP3R_V1_ADDRESS:str:0x3364BF0a8DcB15E463E6659175c90A57ee3d4288}
        keep3r_v2_contract_address: ${KEEP3R_V2_ADDRESS:str:0x85063437C02Ba7F4f82F898859e4992380DEd3bb}
        use_v2: ${USE_KEEPER_V2:bool:true}
        participant_to_swap_pref: ${SWAP_PREF:list:[["0x0000000000000000000000000000000000000000","k3pr"]]}
        tendermint_p2p_url: ${TENDERMINT_P2P_URL_2:str:node2:26656}
        service_endpoint_base: ${SERVICE_ENDPOINT_BASE:str:https://dummy_service.autonolas.tech/}
3:
  models:
    params:
      args:
        setup: *id001
        bonding_asset: ${BONDING_ASSET:str:0x0000000000000000000000000000000000000000}
        bond_amount: ${BOND_AMOUNT:int:1}
        reset_pause_duration: ${RESET_PAUSE_DURATION:int:60}
        service_registry_address: '0x1cEe30D08943EB58EFF84DD1AB44a6ee6FEff63a'
        on_chain_service_id: ${ON_CHAIN_SERVICE_ID:int:null}
        share_tm_config_on_startup: ${USE_ACN:bool:false}
        use_termination: ${USE_TERMINATION:bool:false}
        use_flashbots: ${USE_FLASHBOTS:bool:false}
        supported_jobs_to_package_hash: ${JOBS_TO_HASH:list:null}
        keep3r_v1_contract_address: ${KEEP3R_V1_ADDRESS:str:0x3364BF0a8DcB15E463E6659175c90A57ee3d4288}
        keep3r_v2_contract_address: ${KEEP3R_V2_ADDRESS:str:0x85063437C02Ba7F4f82F898859e4992380DEd3bb}
        use_v2: ${USE_KEEPER_V2:bool:true}
        participant_to_swap_pref: ${SWAP_PREF:list:[["0x0000000000000000000000000000000000000000","k3pr"]]}
        tendermint_p2p_url: ${TENDERMINT_P2P_URL_3:str:node3:26656}
        service_endpoint_base: ${SERVICE_ENDPOINT_BASE:str:https://dummy_service.autonolas.tech/}
---
public_id: valory/ledger:0.19.0
type: connection
0:
  config:
    ledger_apis:
      ethereum:
        address: ${SERVICE_RPC_0:str:http://127.0.0.1:8545}
        chain_id: 5
      ethereum_flashbots:
        flashbots_builders: ${FLASHBOTS_BUILDERS_0:list:[["flashbotsBuilder", "https://relay-goerli.flashbots.net"]]}
        authentication_private_key: ${FLASHBOTS_PRIVATE_KEY_0:str:null}
      arbitrum:
        address: ${ARBITRUM_RPC_0:str:http://127.0.0.1:8545}
        chain_id: ${ARBITRUM_CHAIN_ID:int:421613}
      consensys:
        address: ${CONSENSYS_RPC_0:str:http://127.0.0.1:8545}
        chain_id: ${CONSENSYS_CHAIN_ID:int:1337}
      bnb:
        address: ${BNB_RPC_0:str:http://127.0.0.1:8545}
        chain_id: ${BNB_CHAIN_ID:int:56}
      gnosis:
        address: ${GNOSIS_RPC_0:str:http://127.0.0.1:8545}
        chain_id: ${GNOSIS_CHAIN_ID:int:100}
      zksync:
        address: ${ZKSYNC_RPC_0:str:http://127.0.0.1:8545}
        chain_id: ${ZKSYNC_CHAIN_ID:int:324}
1:
  config:
    ledger_apis:
      ethereum:
        address: ${SERVICE_RPC_1:str:http://127.0.0.1:8545}
        chain_id: 5
      ethereum_flashbots:
        flashbot_relayer_uri: ${FLASHBOTS_BUILDERS_1:list:[["flashbotsBuilder", "https://relay-goerli.flashbots.net"]]}
        authentication_private_key: ${FLASHBOTS_PRIVATE_KEY_1:str:null}
      arbitrum:
        address: ${ARBITRUM_RPC_1:str:http://127.0.0.1:8545}
        chain_id: ${ARBITRUM_CHAIN_ID:int:421613}
      consensys:
        address: ${CONSENSYS_RPC_1:str:http://127.0.0.1:8545}
        chain_id: ${CONSENSYS_CHAIN_ID:int:1337}
      bnb:
        address: ${BNB_RPC_1:str:http://127.0.0.1:8545}
        chain_id: ${BNB_CHAIN_ID:int:56}
      gnosis:
        address: ${GNOSIS_RPC_1:str:http://127.0.0.1:8545}
        chain_id: ${GNOSIS_CHAIN_ID:int:100}
      zksync:
        address: ${ZKSYNC_RPC_1:str:http://127.0.0.1:8545}
        chain_id: ${ZKSYNC_CHAIN_ID:int:324}
2:
  config:
    ledger_apis:
      ethereum:
        address: ${SERVICE_RPC_2:str:http://127.0.0.1:8545}
        chain_id: 5
      ethereum_flashbots:
        flashbot_relayer_uri: ${FLASHBOTS_BUILDERS_2:list:[["flashbotsBuilder", "https://relay-goerli.flashbots.net"]]}
        authentication_private_key: ${FLASHBOTS_PRIVATE_KEY_2:str:null}
      arbitrum:
        address: ${ARBITRUM_RPC_2:str:http://127.0.0.1:8545}
        chain_id: ${ARBITRUM_CHAIN_ID:int:421613}
      consensys:
        address: ${CONSENSYS_RPC_2:str:http://127.0.0.1:8545}
        chain_id: ${CONSENSYS_CHAIN_ID:int:1337}
      bnb:
        address: ${BNB_RPC_2:str:http://127.0.0.1:8545}
        chain_id: ${BNB_CHAIN_ID:int:56}
      gnosis:
        address: ${GNOSIS_RPC_2:str:http://127.0.0.1:8545}
        chain_id: ${GNOSIS_CHAIN_ID:int:100}
      zksync:
        address: ${ZKSYNC_RPC_2:str:http://127.0.0.1:8545}
        chain_id: ${ZKSYNC_CHAIN_ID:int:324}
3:
  config:
    ledger_apis:
      ethereum:
        address: ${SERVICE_RPC_3:str:http://127.0.0.1:8545}
        chain_id: 5
      ethereum_flashbots:
        flashbot_relayer_uri: ${FLASHBOTS_BUILDERS_3:list:[["flashbotsBuilder", "https://relay-goerli.flashbots.net"]]}
        authentication_private_key: ${FLASHBOTS_PRIVATE_KEY_3:str:null}
      arbitrum:
        address: ${ARBITRUM_RPC_3:str:http://127.0.0.1:8545}
        chain_id: ${ARBITRUM_CHAIN_ID:int:421613}
      consensys:
        address: ${CONSENSYS_RPC_3:str:http://127.0.0.1:8545}
        chain_id: ${CONSENSYS_CHAIN_ID:int:1337}
      bnb:
        address: ${BNB_RPC_3:str:http://127.0.0.1:8545}
        chain_id: ${BNB_CHAIN_ID:int:56}
      gnosis:
        address: ${GNOSIS_RPC_3:str:http://127.0.0.1:8545}
        chain_id: ${GNOSIS_CHAIN_ID:int:100}
      zksync:
        address: ${ZKSYNC_RPC_3:str:http://127.0.0.1:8545}
        chain_id: ${ZKSYNC_CHAIN_ID:int:324}
