name: counter
author: valory
version: 0.1.0
description: A set of agents incrementing a counter
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint:
  README.md: bafybeidoybzzjch4djhhafqm4e4jcrpaqmlthntcnonlsjtowwpykbc5xi
fingerprint_ignore_patterns: []
number_of_agents: 1
agent: valory/counter:0.1.0:bafybeicj4xcljp3qjjpf2zvtw3za7h4lrw5zvehvl7eyglww6k4fyzg4qu
network: hardhat
